import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useEffect, useState } from "react";
import { ObjectId } from "mongodb";

interface Indications {
  idInd: string;
  text: string;
}

interface NocData {
  _id: ObjectId;
  name: string;
  code: string;
  definiton: string;
  indications: Indications[];
}

interface NicData {
  _id: ObjectId;
  name: string;
  definition: string;
  blue: string[];
  interventions_nursing: string[];
  interventions_optional: string[];
}

const Home: NextPage = () => {
  const [nicSearch, setNicSearch] = useState<string>();
  const [nocSearch, setNocSearch] = useState<string>();
  const [responseNoc, setResponseNoc] = useState<NocData[]>();
  const [responseNic, setResponseNic] = useState<NicData[]>();
  const [buttonNic, setButtonNic] = useState<boolean>(false);
  const [buttonNoc, setButtonNoc] = useState<boolean>(false);
  const [n, setN] = useState<string>("");

  function rowColor(aa: string) {
    if (aa) {
      return "green";
    } else {
      return "pink";
    }
  }

  useEffect(() => {
    async function getNic() {
      try {
        const response = await axios.get(
          `http://localhost:3000/api/nic/${nicSearch}`
        );
        setResponseNic(response.data);
        console.log(buttonNic);
        console.log(responseNic);
      } catch (err) {
        console.error("error Nic");
      }
    }
    getNic();
  }, [buttonNic]);

  useEffect(() => {}, [buttonNic]);

  useEffect(() => {
    async function getNoc() {
      try {
        const response = await axios.get(
          `http://localhost:3000/api/noc/${nocSearch}`
        );
        setResponseNoc(response.data);
        console.log(buttonNoc);
        console.log(responseNoc);
      } catch (err) {
        console.error("error Noc");
      }
    }
    getNoc();
  }, [buttonNoc]);

  function butNic() {
    setButtonNic(!buttonNic);
  }

  function butNoc() {
    setButtonNoc(!buttonNoc);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>NandaNocNic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.nocDiv}>
          <h1 className={styles.title}>NOC</h1>
          <input
            type="text"
            value={nocSearch}
            onChange={(e) => setNocSearch(e.target.value)}
            placeholder="Pesquise sintomas no Noc"
          />
          <button onClick={() => butNoc()}>Noc</button>

          <div className={styles.info}>
            {responseNoc?.map((e) => (
              <div
                className={styles.infoDivison}
                style={{ backgroundColor: rowColor(n) }}
              >
                <p>Name:{e.name}</p>
              </div>
            ))}
          </div>
        </div>

        <div className={styles.nicDiv}>
          <h1 className={styles.title}>NIC</h1>
          <input
            type="text"
            value={nicSearch}
            onChange={(e) => setNicSearch(e.target.value)}
            placeholder="Pesquise sintomas no Nic"
          />
          <button onClick={() => butNic()}>Nic</button>

          <div className={styles.info}>
            {responseNic?.map((e) => (
              <div
                key={e.name}
                className={styles.infoDivison}
                style={{ backgroundColor: rowColor(n) }}
              >
                <p>Name:{e.name}</p>
              </div>
            ))}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
